sonar.projectKey=bar-management
sonar.projectName=Bar Management
sonar.sources=app/backend/src,app/frontend/src,app/packages/contracts/src
sonar.tests=app/backend/src,app/frontend/src,app/packages/contracts/src,app/backend/test,app/frontend/e2e
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,app/frontend/public/mockServiceWorker.js,app/backend/src/providers/database/migrations/**
